spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/paps
    username: papsadmin
    password: papsadmin
  sql:
    init:
      mode: always
  jpa:
    # Hibernate is an ORM (Object Relational Mapper)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  mail:
    mail:
      host: smtp.gmail.com
    password: mobgcqpnwfibnlzx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: 'ifro.paps@gmail.com '
