name: CI/CD PIPELINE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to fly.io
    steps:
      - uses: action/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app paps
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}



